<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aktivitas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aktivitas by id_aktivitas
     */
    function get_aktivitas($id_aktivitas)
    {
        return $this->db->get_where('aktivitas',array('id_aktivitas'=>$id_aktivitas))->row_array();
    }
        
    /*
     * Get all aktivitas
     */
    function get_all_aktivitas()
    {
        return $this->db->get('aktivitas')->result_array();
    }
        
    /*
     * function to add new aktivitas
     */
    function add_aktivitas($params)
    {
        $this->db->insert('aktivitas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update aktivitas
     */
    function update_aktivitas($id_aktivitas,$params)
    {
        $this->db->where('id_aktivitas',$id_aktivitas);
        return $this->db->update('aktivitas',$params);
    }
    
    /*
     * function to delete aktivitas
     */
    function delete_aktivitas($id_aktivitas)
    {
        return $this->db->delete('aktivitas',array('id_aktivitas'=>$id_aktivitas));
    }
}
