<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Jobdes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    function viewJob($id_jadwal)
    {
        $this->db->join('jadwal', 'jadwal.id_jadwal = jobdes.id_jadwal');
        return $this->db->get_where('jobdes', array('jobdes.id_jadwal' => $id_jadwal))->result_array();
    }

    function add_aktivitas($params)
    {
        return $this->db->insert('aktivitas', $params);
    }
    /*
     * Get jobdes by id_jobdes
     */
    function get_jobdes($id_jobdes)
    {
        return $this->db->get_where('jobdes', array('id_jobdes' => $id_jobdes))->row_array();
    }
    function all_jobdes()
    {
        $this->db->select('*');
        $this->db->from('jobdes');
        $this->db->join('profile', 'profile.id_profile = jobdes.id_profile');
        $this->db->join('user', 'user.id_user = jobdes.id_user');
        return $this->db->get()->result_array();
    }

    /*
     * Get all jobdes
     */
    function get_all_jobdes()
    {
        $this->db->order_by('id_jobdes', 'desc');
        return $this->db->get('jobdes')->result_array();
    }

    /*
     * function to add new jobdes
     */
    function add_jobdes($params)
    {
        $this->db->insert('jobdes', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update jobdes
     */
    function update_jobdes($id_jobdes, $params)
    {
        $this->db->where('id_jobdes', $id_jobdes);
        return $this->db->update('jobdes', $params);
    }

    /*
     * function to delete jobdes
     */
    function delete_jobdes($id_jobdes)
    {
        return $this->db->delete('jobdes', array('id_jobdes' => $id_jobdes));
    }

    function getJob($idprofile)
    {
        $this->db->join('jadwal', 'jadwal.id_jadwal=jobdes.id_jadwal');
        return $this->db->get_where('jobdes', array('id_profile' => $idprofile))->result_array();
    }
}
