<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Profile_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get profile by id_profile
     */
    function get_profile($id_profile)
    {
        return $this->db->get_where('profile', array('id_profile' => $id_profile))->row_array();
    }

    /*
     * Get all profile
     */
    function get_all_profile()
    {
        $this->db->order_by('id_profile', 'desc');
        return $this->db->get('profile')->result_array();
    }

    /*
     * function to add new profile
     */
    function add_profile($params)
    {
        $this->db->insert('profile', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update profile
     */
    function update_profile($id_profile, $params)
    {
        $this->db->where('id_profile', $id_profile);
        return $this->db->update('profile', $params);
    }

    /*
     * function to delete profile
     */
    function delete_profile($id_profile)
    {
        return $this->db->delete('profile', array('id_profile' => $id_profile));
    }

    function get_jobdes($id_user)
    {
        $this->db->join('profile', 'jadwal.id_profile = profile.id_profile');
        return $this->db->get_where('jadwal', array('id_user' => $id_user))->result_array();
    }
    function all_jobdes()
    {
        $this->db->join('profile', 'jadwal.id_profile = profile.id_profile');
        return $this->db->get('jadwal')->result_array();
    }
}
